# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        ClothstudioBundle\Entity\User: bcrypt
        ClothstudioBundle\Entity\Customer: bcrypt
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        
        in_memory:
            memory: ~
            
        login:
            entity:
                class: ClothstudioBundle:Customer
                property: cEmail

    firewalls:
        
        
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            
            pattern:    ^/
            http_basic: ~
            provider: login
            form_login:    
                username_parameter: _username
                password_parameter: _password
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: profile
            logout:     true  
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            
    access_control:
        - { path: ^/http://127.0.0.1:8000, roles: ROLE_USER }
        #- { path: ^/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        