<?php

namespace ClothstudioBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function editUserdata($user)
    {
        $qb =  $this->createQueryBuilder();
        $userdata = $qb->update('ClothstudioBundle:User')
                    ->set('username',$user->getUsername());
            
    }
}
