<?php

namespace Proxies\__CG__\ClothstudioBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \ClothstudioBundle\Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cFacebookID', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cTwitterID', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cFirstName', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLastName', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPhone', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cZip', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cEmail', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPassword', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cGender', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cHeight', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cWeight', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cTopSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cDressSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cBraSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPantSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cWaistSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cShoesSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cBodyShape', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLikeStyles', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLikeColorPalettes', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cIdeallySpentForCategories', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cCreatedDate', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cModifiedDate', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cStatus', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'ProfilePicture'];
        }

        return ['__isInitialized__', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'id', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cFacebookID', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cTwitterID', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cFirstName', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLastName', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPhone', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cZip', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cEmail', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPassword', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cGender', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cHeight', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cWeight', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cTopSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cDressSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cBraSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cPantSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cWaistSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cShoesSize', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cBodyShape', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLikeStyles', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cLikeColorPalettes', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cIdeallySpentForCategories', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cCreatedDate', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cModifiedDate', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'cStatus', '' . "\0" . 'ClothstudioBundle\\Entity\\Customer' . "\0" . 'ProfilePicture'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCFacebookID($cFacebookID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCFacebookID', [$cFacebookID]);

        return parent::setCFacebookID($cFacebookID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCFacebookID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCFacebookID', []);

        return parent::getCFacebookID();
    }

    /**
     * {@inheritDoc}
     */
    public function setCTwitterID($cTwitterID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCTwitterID', [$cTwitterID]);

        return parent::setCTwitterID($cTwitterID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCTwitterID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCTwitterID', []);

        return parent::getCTwitterID();
    }

    /**
     * {@inheritDoc}
     */
    public function setCFirstName($cFirstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCFirstName', [$cFirstName]);

        return parent::setCFirstName($cFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCFirstName', []);

        return parent::getCFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCLastName($cLastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCLastName', [$cLastName]);

        return parent::setCLastName($cLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCLastName', []);

        return parent::getCLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCPhone($cPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCPhone', [$cPhone]);

        return parent::setCPhone($cPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCPhone', []);

        return parent::getCPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCZip($cZip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCZip', [$cZip]);

        return parent::setCZip($cZip);
    }

    /**
     * {@inheritDoc}
     */
    public function getCZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCZip', []);

        return parent::getCZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCEmail($cEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCEmail', [$cEmail]);

        return parent::setCEmail($cEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCEmail', []);

        return parent::getCEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCPassword($cPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCPassword', [$cPassword]);

        return parent::setCPassword($cPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getCPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCPassword', []);

        return parent::getCPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setCGender($cGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCGender', [$cGender]);

        return parent::setCGender($cGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getCGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCGender', []);

        return parent::getCGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setCHeight($cHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCHeight', [$cHeight]);

        return parent::setCHeight($cHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCHeight', []);

        return parent::getCHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setCWeight($cWeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCWeight', [$cWeight]);

        return parent::setCWeight($cWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCWeight', []);

        return parent::getCWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setCTopSize($cTopSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCTopSize', [$cTopSize]);

        return parent::setCTopSize($cTopSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCTopSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCTopSize', []);

        return parent::getCTopSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCDressSize($cDressSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCDressSize', [$cDressSize]);

        return parent::setCDressSize($cDressSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCDressSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCDressSize', []);

        return parent::getCDressSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCBraSize($cBraSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCBraSize', [$cBraSize]);

        return parent::setCBraSize($cBraSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCBraSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCBraSize', []);

        return parent::getCBraSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCPantSize($cPantSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCPantSize', [$cPantSize]);

        return parent::setCPantSize($cPantSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCPantSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCPantSize', []);

        return parent::getCPantSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCWaistSize($cWaistSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCWaistSize', [$cWaistSize]);

        return parent::setCWaistSize($cWaistSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCWaistSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCWaistSize', []);

        return parent::getCWaistSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCShoesSize($cShoesSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCShoesSize', [$cShoesSize]);

        return parent::setCShoesSize($cShoesSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCShoesSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCShoesSize', []);

        return parent::getCShoesSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setCBodyShape($cBodyShape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCBodyShape', [$cBodyShape]);

        return parent::setCBodyShape($cBodyShape);
    }

    /**
     * {@inheritDoc}
     */
    public function getCBodyShape()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCBodyShape', []);

        return parent::getCBodyShape();
    }

    /**
     * {@inheritDoc}
     */
    public function setCLikeStyles($cLikeStyles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCLikeStyles', [$cLikeStyles]);

        return parent::setCLikeStyles($cLikeStyles);
    }

    /**
     * {@inheritDoc}
     */
    public function getCLikeStyles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCLikeStyles', []);

        return parent::getCLikeStyles();
    }

    /**
     * {@inheritDoc}
     */
    public function setCLikeColorPalettes($cLikeColorPalettes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCLikeColorPalettes', [$cLikeColorPalettes]);

        return parent::setCLikeColorPalettes($cLikeColorPalettes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCLikeColorPalettes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCLikeColorPalettes', []);

        return parent::getCLikeColorPalettes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCIdeallySpentForCategories($cIdeallySpentForCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCIdeallySpentForCategories', [$cIdeallySpentForCategories]);

        return parent::setCIdeallySpentForCategories($cIdeallySpentForCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCIdeallySpentForCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCIdeallySpentForCategories', []);

        return parent::getCIdeallySpentForCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCCreatedDate($cCreatedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCCreatedDate', [$cCreatedDate]);

        return parent::setCCreatedDate($cCreatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCCreatedDate', []);

        return parent::getCCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCModifiedDate($cModifiedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCModifiedDate', [$cModifiedDate]);

        return parent::setCModifiedDate($cModifiedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCModifiedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCModifiedDate', []);

        return parent::getCModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCStatus($cStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCStatus', [$cStatus]);

        return parent::setCStatus($cStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCStatus', []);

        return parent::getCStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilePicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilePicture', []);

        return parent::getProfilePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfilePicture($ProfilePicture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfilePicture', [$ProfilePicture]);

        return parent::setProfilePicture($ProfilePicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function equals(\Symfony\Component\Security\Core\User\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', [$user]);

        return parent::equals($user);
    }

}
